[package]
name = "zs-filecrawler"
version = "0.0.0"
authors = ["Erik Zscheile <erik.zscheile@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/zserik/zs-filecrawler"

[dependencies]
bincode = "1.1.4"
clap = "2.33.0"
digest = "0.8.1"
flate2 = "1.0.9"
generic-array = { version = "0.12.0", features = ["serde"] }
hashbrown = { version = "0.5.0", features = ["serde"] }
hex = "0.3.2"
indoc = "0.3.3"
log = "0.4.7"
readfilez = "0.1.3"
serde = { version = "1.0.97", features = ["derive"] }
sha2 = "0.8.0"
signal-hook = "0.1.10"
simplelog = "0.6.0"
text_io = "0.1.7"
